// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQQLCGL9Pz93oNU9O1zKsPq-FEk9xOBCM',
    appId: '1:567770648989:web:538b5760d2751c65481f74',
    messagingSenderId: '567770648989',
    projectId: 'app-focus-cop',
    authDomain: 'app-focus-cop.firebaseapp.com',
    storageBucket: 'app-focus-cop.appspot.com',
    measurementId: 'G-REXBS1HH17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX--FEphgEZXOVDyz68dnneWBjfb9bG2I',
    appId: '1:567770648989:android:cb521a314740b5d4481f74',
    messagingSenderId: '567770648989',
    projectId: 'app-focus-cop',
    storageBucket: 'app-focus-cop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVrvutvM63IGGsjTi8rDBfQ4kAfegvF2A',
    appId: '1:567770648989:ios:cc6a89fc61c9d75f481f74',
    messagingSenderId: '567770648989',
    projectId: 'app-focus-cop',
    storageBucket: 'app-focus-cop.appspot.com',
    iosBundleId: 'com.example.focus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVrvutvM63IGGsjTi8rDBfQ4kAfegvF2A',
    appId: '1:567770648989:ios:080968a241e8728f481f74',
    messagingSenderId: '567770648989',
    projectId: 'app-focus-cop',
    storageBucket: 'app-focus-cop.appspot.com',
    iosBundleId: 'com.example.focus.RunnerTests',
  );
}
