import '../chars/logo_enemy.dart';
import '../chuck_environment/ground_block.dart';
import '../chuck_environment/platform_block.dart';
import '../chuck_environment/star.dart';

import 'package:flame/components.dart';

class Block {
  final Vector2 gridPosition;
  final Type blockType;
  Block(this.gridPosition, this.blockType);
}

final segments = [
  segment0,
  segment1,
  segment2,
  segment3,
  segment4,
  segment5,
  segment6,
  segment7,
];



final segment0 = [
  Block(Vector2(0, 0), GroundBlock),
  Block(Vector2(1, 0), GroundBlock),
  Block(Vector2(2, 0), GroundBlock),
  Block(Vector2(3, 0), GroundBlock),
  Block(Vector2(4, 0), GroundBlock),
  Block(Vector2(5, 0), GroundBlock),
  Block(Vector2(7, 1), LogoEnemy),
  Block(Vector2(5, 3), PlatformBlock),
  Block(Vector2(6, 0), GroundBlock),
  Block(Vector2(6, 3), PlatformBlock),
  Block(Vector2(7, 0), GroundBlock),
  Block(Vector2(7, 3), PlatformBlock),
  Block(Vector2(8, 0), GroundBlock),
  Block(Vector2(8, 3), PlatformBlock),
  Block(Vector2(9, 0), GroundBlock),
];

final segment1 = [
  Block(Vector2(0, 0), GroundBlock),
  Block(Vector2(1, 0), GroundBlock),
  Block(Vector2(1, 1), PlatformBlock),
  Block(Vector2(1, 2), PlatformBlock),
  Block(Vector2(1, 3), PlatformBlock),
  Block(Vector2(2, 6), PlatformBlock),
  Block(Vector2(3, 6), PlatformBlock),
  Block(Vector2(6, 5), PlatformBlock),
  Block(Vector2(7, 5), PlatformBlock),
  Block(Vector2(7, 7), Star),
  Block(Vector2(8, 0), GroundBlock),
  Block(Vector2(8, 1), PlatformBlock),
  Block(Vector2(8, 5), PlatformBlock),
  Block(Vector2(8, 6), LogoEnemy),
  Block(Vector2(9, 0), GroundBlock),
];

final segment2 = [
  Block(Vector2(0, 0), GroundBlock),
  Block(Vector2(1, 0), GroundBlock),
  Block(Vector2(2, 0), GroundBlock),
  Block(Vector2(3, 0), GroundBlock),
  Block(Vector2(3, 3), PlatformBlock),
  Block(Vector2(4, 0), GroundBlock),
  Block(Vector2(4, 3), PlatformBlock),
  Block(Vector2(5, 0), GroundBlock),
  Block(Vector2(5, 3), PlatformBlock),
  Block(Vector2(5, 4), LogoEnemy),
  Block(Vector2(6, 0), GroundBlock),
  Block(Vector2(6, 3), PlatformBlock),
  Block(Vector2(6, 4), PlatformBlock),
  Block(Vector2(6, 5), PlatformBlock),
  Block(Vector2(6, 7), Star),
  Block(Vector2(7, 0), GroundBlock),
  Block(Vector2(8, 0), GroundBlock),
  Block(Vector2(9, 0), GroundBlock),
];

final segment3 = [
  Block(Vector2(0, 0), GroundBlock),
  Block(Vector2(1, 0), GroundBlock),
  Block(Vector2(1, 1), LogoEnemy),
  Block(Vector2(2, 0), GroundBlock),
  Block(Vector2(2, 1), PlatformBlock),
  Block(Vector2(2, 2), PlatformBlock),
  Block(Vector2(4, 4), PlatformBlock),
  Block(Vector2(6, 6), PlatformBlock),
  Block(Vector2(7, 0), GroundBlock),
  Block(Vector2(7, 1), PlatformBlock),
  Block(Vector2(8, 0), GroundBlock),
  Block(Vector2(8, 8), Star),
  Block(Vector2(9, 0), GroundBlock),
];

final segment4 = [
  Block(Vector2(0, 0), GroundBlock),
  Block(Vector2(1, 0), GroundBlock),
  Block(Vector2(2, 0), GroundBlock),
  Block(Vector2(2, 3), PlatformBlock),
  Block(Vector2(3, 0), GroundBlock),
  Block(Vector2(3, 1), LogoEnemy),
  Block(Vector2(3, 3), PlatformBlock),
  Block(Vector2(4, 0), GroundBlock),
  Block(Vector2(5, 0), GroundBlock),
  Block(Vector2(5, 5), PlatformBlock),
  Block(Vector2(6, 0), GroundBlock),
  Block(Vector2(6, 5), PlatformBlock),
  Block(Vector2(6, 7), Star),
  Block(Vector2(7, 0), GroundBlock),
  Block(Vector2(8, 0), GroundBlock),
  Block(Vector2(8, 3), PlatformBlock),
  Block(Vector2(9, 0), GroundBlock),
  Block(Vector2(9, 1), LogoEnemy),
  Block(Vector2(9, 3), PlatformBlock),
];

final segment5 = [  Block(Vector2(9, 7), PlatformBlock),
  Block(Vector2(9, 6), PlatformBlock),
  Block(Vector2(6, 5), LogoEnemy),
  Block(Vector2(8, 5), StarBlock),
  Block(Vector2(9, 5), PlatformBlock),
  Block(Vector2(5, 4), GroundBlock),
  Block(Vector2(6, 4), GroundBlock),
  Block(Vector2(7, 4), GroundBlock),
  Block(Vector2(8, 4), GroundBlock),
  Block(Vector2(9, 4), PlatformBlock),
  Block(Vector2(1, 1), LogoEnemy),
  Block(Vector2(0, 0), GroundBlock),
  Block(Vector2(1, 0), GroundBlock),
  Block(Vector2(2, 0), GroundBlock),
  Block(Vector2(3, 0), GroundBlock),
  Block(Vector2(9, 0), GroundBlock),
];
final segment6 = [  Block(Vector2(8, 7), LogoEnemy),
  Block(Vector2(9, 7), StarBlock),
  Block(Vector2(3, 6), LogoEnemy),
  Block(Vector2(7, 6), PlatformBlock),
  Block(Vector2(8, 6), PlatformBlock),
  Block(Vector2(9, 6), PlatformBlock),
  Block(Vector2(2, 5), PlatformBlock),
  Block(Vector2(3, 5), PlatformBlock),
  Block(Vector2(4, 5), GroundBlock),
  Block(Vector2(7, 3), LogoEnemy),
  Block(Vector2(2, 2), LogoEnemy),
  Block(Vector2(5, 2), GroundBlock),
  Block(Vector2(6, 2), GroundBlock),
  Block(Vector2(7, 2), PlatformBlock),
  Block(Vector2(8, 2), PlatformBlock),
  Block(Vector2(1, 1), PlatformBlock),
  Block(Vector2(2, 1), PlatformBlock),
  Block(Vector2(3, 1), PlatformBlock),
  Block(Vector2(1, 0), GroundBlock),
  Block(Vector2(2, 0), GroundBlock),
  Block(Vector2(3, 0), GroundBlock),
  Block(Vector2(7, 0), GroundBlock),
  Block(Vector2(8, 0), GroundBlock),
  Block(Vector2(9, 0), GroundBlock),
];

final segment7 = [  Block(Vector2(2, 7), LogoEnemy),
  Block(Vector2(3, 7), StarBlock),
  Block(Vector2(5, 7), LogoEnemy),
  Block(Vector2(1, 6), PlatformBlock),
  Block(Vector2(2, 6), PlatformBlock),
  Block(Vector2(3, 6), PlatformBlock),
  Block(Vector2(4, 6), PlatformBlock),
  Block(Vector2(5, 6), PlatformBlock),
  Block(Vector2(6, 6), PlatformBlock),
  Block(Vector2(6, 4), StarBlock),
  Block(Vector2(4, 3), PlatformBlock),
  Block(Vector2(5, 3), PlatformBlock),
  Block(Vector2(6, 3), PlatformBlock),
  Block(Vector2(7, 3), PlatformBlock),
  Block(Vector2(4, 1), LogoEnemy),
  Block(Vector2(7, 1), LogoEnemy),
  Block(Vector2(1, 0), GroundBlock),
  Block(Vector2(2, 0), GroundBlock),
  Block(Vector2(3, 0), GroundBlock),
  Block(Vector2(4, 0), GroundBlock),
  Block(Vector2(5, 0), GroundBlock),
  Block(Vector2(6, 0), GroundBlock),
  Block(Vector2(7, 0), GroundBlock),
  Block(Vector2(8, 0), GroundBlock),
  Block(Vector2(9, 0), GroundBlock),
];